sudo: required
services:
    - docker

before_install:
    - docker build - t yuliyalmaty/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true yuliyalmaty/react-test npm test

after_success:
    - docker build -t yuliyalmaty/multi-client ./client
    - docker build -t yuliyalmaty/multi-nginx ./nginx
    - docker build -t yuliyalmaty/multi-server ./server
    - docker build -t yuliyalmaty/multi-worker ./worker
    # Log in to the docker CLI
    echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push yuliyalmaty/multi-client
    - docker push yuliyalmaty/multi-nginx
    - docker push yuliyalmaty/multi-server    
    - docker push yuliyalmaty/multi-worker
